# Generated by Django 4.0 on 2024-11-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0002_alter_comment_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="is_active",
            field=models.BooleanField(unique=True, verbose_name="Активная?"),
        ),
    ]
