# Generated by Django 4.0 on 2024-11-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0003_alter_image_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активная?"),
        ),
    ]
